name: Docker Image CI

on:
  push:
    tags:
        - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: MichaelJBerk
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          tags: 
            dev
          
